TheScouts/Controllers/ApplicationController.cs
using System;
using System.Data;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TheScouts.Models;
using TheScouts.Services;

namespace TheScouts.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly IApplicationService _service;
        private readonly IWebHostEnvironment _environment;
        private readonly UserManager<ApplicationUser> _userManager;

        public ApplicationController(IApplicationService service, IWebHostEnvironment environment, UserManager<ApplicationUser> userManager)
        {
            _service = service;
            _environment = environment;
            _userManager = userManager;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            string userId = _userManager.GetUserId(User);

            if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
            {
                var allApplications = await _service.GetAllAsync();
                return View(allApplications);
            }
            else
            {
                var userApplications = await _service.FindApplicationsByUserIdAsync(userId);
                return View(userApplications);
            }
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Create(int positionId)
        {
            var model = new Application
            {
                Id = positionId,
            };

            var position = await _service.FindPositionAsync(positionId);
            if(position != null)
            {
                ViewData["JobTitle"] = position.JobTitle;
                ViewData["Location"] = $"{position.City}, {position.Country}";
            }
            else
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Application application, IFormFile resume)
        {
            if (ModelState.IsValid)
            {
                string userId = _userManager.GetUserId(User);
                application.UserId = userId;

                if (resume != null && resume.Length > 0)
                {
                    var resumes = Path.Combine(_environment.WebRootPath, "resumes");
                    var fileName = Guid.NewGuid().ToString() + "_" + application.Name + "-" + application.Surname + "-" + Path.GetFileName(resume.FileName);
                    var filePath = Path.Combine(resumes, fileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await resume.CopyToAsync(fileStream);
                    }

                    application.Resume = "/resumes/" + fileName;
                }

                await _service.AddAsync(application);
                return RedirectToAction("SuccessMessage");
            }

            return View(application);
        }

        public IActionResult SuccessMessage()
        {
            ViewBag.SuccessMessage = "Application submitted successfully!";

            return PartialView("_SuccessMessage", ViewBag.SuccessMessage);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Applications(int id)
        {
            var applications = await _service.FindApplicationsAsync(id);
            var positionName = await _service.GetPositionNameByIdAsync(id);

            ViewBag.PositionName = positionName;

            return View(applications);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Search(string searchTerm)
        {
            var applications = await _service.GetAllAsync();

            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                applications = applications
                    .Where(application =>
                        application.Name.ToLower().Contains(searchTerm.ToLower()) ||
                        application.Surname.ToLower().Contains(searchTerm.ToLower())
                    )
                    .ToList();
            }

            return View("Index", applications);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> UpdateStatus(int applicationId, string status)
        {
            var updatedApplication = await _service.UpdateStatus(applicationId, status);

            if (updatedApplication != null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return NotFound();
            }
        }
    }
}

TheScouts/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheScouts.Services;
using TheScouts.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace TheScouts.Controllers
{
    public class JobsController : Controller
    {
        private readonly IPositionService _service;

        public JobsController(IPositionService service)
        {
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var positions = await _service.GetAllAsync();
            return View(positions);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var position = await _service.FindOneAsync(id);
            return View(position);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Create(Position position)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(position);
                return RedirectToAction("Index");
            }
            return View(position);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Delete(int id)
        {
            var position = await _service.FindOneAsync(id);
            if(position != null)
            {
                await _service.DeleteAsync(id);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Edit(int id)
        {
            var position = await _service.FindOneAsync(id);
            if (position == null)
            {
                return NotFound();
            }
            return View(position);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Edit(Position position)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(position);
                return RedirectToAction("Index");
            }
            return View(position);
        }

        [HttpGet]
        public async Task<IActionResult> Search(string searchTerm, string category)
        {
            var positions = await _service.GetAllAsync();

            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                positions = positions
                    .Where(position => position.JobTitle.ToLower().Contains(searchTerm.ToLower()))
                    .ToList();
            }

            if (!string.IsNullOrWhiteSpace(category) && category != "All")
            {
                positions = positions
                    .Where(position => position.Country.ToLower() == category.ToLower())
                    .ToList();
            }

            ViewData["Category"] = category ?? "All";

            return View("Index", positions);
        }
    }
}

TheScouts/Views/Jobs/Create.cshtml
@model TheScouts.Models.Position

@{
    ViewData["Title"] = "Add Position";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Create", "Jobs", FormMethod.Post, new { @class = "position-form" }))
{
    <h2>Add Position</h2>

    <div class="form-content">
        @Html.LabelFor(model => model.Country, new { @class = "control-label" })
        @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Country" } })
        @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
    </div>
    <div class="form-content">
        @Html.LabelFor(model => model.City, new { @class = "control-label" })
        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter City" } })
        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
    </div>
    <div class="form-content">
        @Html.LabelFor(model => model.JobTitle, new { @class = "control-label" })
        @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Job Title" } })
        @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
    </div>
    <div class="form-content">
        @Html.LabelFor(model => model.JobDescription, new { @class = "control-label" })
        @Html.TextAreaFor(model => model.JobDescription, new { @class = "form-control autosize", placeholder = "Enter Job Description" })
        @Html.ValidationMessageFor(model => model.JobDescription, "", new { @class = "text-danger" })
    </div>
    <button type="submit" class="btn button-primary">Add</button>
}

TheScouts/Views/Jobs/Details.cshtml
@model TheScouts.Models.Position

@{
    ViewData["Title"] = "Position Details";
}

<div class="d-flex justify-content-center my-5">
    <h1 class="display-5">Open Position</h1>
</div>
<div class="details-container">
    <p class="display-6 details-title">@Model.JobTitle in @Model.City, @Model.Country</p>
    <p class="details-description">@Model.JobDescription</p>
</div>
<div class="my-5">
    @Html.ActionLink("Apply Online", "Create", "Application", new { positionId = Model.Id }, new { @class = "btn button-primary" })
</div>

TheScouts/Views/Jobs/Edit.cshtml
@model TheScouts.Models.Position

@{
    ViewData["Title"] = "Edit Position";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("Edit", "Jobs", FormMethod.Post, new { @class = "position-form" }))
{
    <h2>Edit Position</h2>

    @Html.HiddenFor(model => model.Id)
    <div class="form-content">
        @Html.LabelFor(model => model.Country, new { @class = "control-label" })
        @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Country" } })
        @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
    </div>
    <div class="form-content">
        @Html.LabelFor(model => model.City, new { @class = "control-label" })
        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter City" } })
        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
    </div>
    <div class="form-content">
        @Html.LabelFor(model => model.JobTitle, new { @class = "control-label" })
        @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter Job Title" } })
        @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
    </div>
    <div class="form-content">
        @Html.LabelFor(model => model.JobDescription, new { @class = "control-label" })
        @Html.TextAreaFor(model => model.JobDescription, new { @class = "form-control autosize", placeholder = "Enter Job Description" })
        @Html.ValidationMessageFor(model => model.JobDescription, "", new { @class = "text-danger" })
    </div>
    <button type="submit" class="btn button-primary">Save Changes</button>
}

TheScouts/Views/Jobs/Index.cshtml
@{
    ViewData["Title"] = "Positions";
}
@model IEnumerable<TheScouts.Models.Position>

<div class="d-flex justify-content-center my-5">
    <h1 class="display-5">Open Positions</h1>
</div>
<div>
    @if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
    {
        @Html.ActionLink("Add Position", "Create", "Jobs", new { }, new { @class = "btn button-primary" })
    }
</div>
<div class="my-5 d-flex justify-content-between">
    <div style="display: flex; gap: 20px; align-items: center;">
        @Html.ActionLink("All", "Search", "Jobs", new { category = "All" }, new { @class = ViewData["Category"] == null || ViewData["Category"] as string == "All" ? "btn category-secondary" : "category-primary" })
        @Html.ActionLink("Albania", "Search", "Jobs", new { category = "Albania" }, new { @class = ViewData["Category"] as string == "Albania" ? "btn category-secondary" : "category-primary" })
        @Html.ActionLink("Kosovo", "Search", "Jobs", new { category = "Kosovo" }, new { @class = ViewData["Category"] as string == "Kosovo" ? "btn category-secondary" : "category-primary" })
        @Html.ActionLink("Macedonia", "Search", "Jobs", new { category = "Macedonia" }, new { @class = ViewData["Category"] as string == "Macedonia" ? "btn category-secondary" : "category-primary" })
    </div>
    @using (Html.BeginForm("Search", "Jobs", FormMethod.Get))
    {
        <div class="input-group mb-3">
            <input type="text" class="form-control" style="border-color: #212529; " placeholder="Search Position" name="searchTerm" />
            <button class="btn button-primary" type="submit">Search</button>
        </div>
    }
</div>
<div class="d-flex flex-column align-items-center mb-5">
    <table class="table jobs-table text-white">
        <thead>
            <tr>
                <th class="text-start">Location</th>
                <th class="text-middle">Job Title</th>
                <th class="text-end">Job Description</th>
                @if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
                {
                    <th></th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var position in Model)
            {
                @if (Model.Any())
                {
                    <tr>
                        <td class="text-start">@position.City, @position.Country</td>
                        <td class="text-middle">@position.JobTitle</td>
                        <td class="text-end">
                            <a href="@Url.Action("Details", "Jobs", new { id = position.Id })" class="link-primary">Read More &#x2198;</a>
                        </td>
                        @if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
                        {
                            <td>
                                <div class="action-buttons">
                                    @Html.ActionLink("Edit", "Edit", "Jobs", new { id = position.Id }, new { @class = "btn button-secondary" })
                                    @using (Html.BeginForm("Delete", "Jobs", new { id = position.Id }, FormMethod.Post, null, new { onsubmit = "return confirm('Do you want to delete this position?')" }))
                                    {
                                        <button type="submit" class="btn button-secondary">Delete</button>
                                    }
                                    @Html.ActionLink("Applications", "Applications", "Application", new { id = position.Id }, new { @class = "btn button-secondary" })
                                </div>
                            </td>
                        }
                    </tr>
                }
                else
                {
                    <tr>
                        <td>No results found.</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>