TheScouts/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TheScouts.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TheScouts/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TheScouts.Models;
using TheScouts.Services;

namespace TheScouts.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactService _service;

        public ContactController(IContactService service)
        {
            _service = service;
        }

        [HttpGet]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Index()
        {
            var contacts = await _service.GetAllAsync();
            return View(contacts);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Details(int id)
        {
            var contact = await _service.FindOneAsync(id);
            return View(contact);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Contact contact)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(contact);
                return RedirectToAction("SuccessMessage");
            }
            return View(contact);
        }

        public IActionResult SuccessMessage()
        {
            ViewBag.SuccessMessage = "Message submitted successfully!";

            return PartialView("_SuccessMessage", ViewBag.SuccessMessage);
        }
    }
}

TheScouts/Controllers/FaqController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TheScouts.Controllers
{
    public class FaqController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TheScouts/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TheScouts.Services;
using TheScouts.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace TheScouts.Controllers
{
    public class JobsController : Controller
    {
        private readonly IPositionService _service;

        public JobsController(IPositionService service)
        {
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var positions = await _service.GetAllAsync();
            return View(positions);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var position = await _service.FindOneAsync(id);
            return View(position);
        }

        [HttpGet]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Create(Position position)
        {
            if (ModelState.IsValid)
            {
                await _service.AddAsync(position);
                return RedirectToAction("Index");
            }
            return View(position);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Delete(int id)
        {
            var position = await _service.FindOneAsync(id);
            if(position != null)
            {
                await _service.DeleteAsync(id);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Edit(int id)
        {
            var position = await _service.FindOneAsync(id);
            if (position == null)
            {
                return NotFound();
            }
            return View(position);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, SuperAdmin")]
        public async Task<IActionResult> Edit(Position position)
        {
            if (ModelState.IsValid)
            {
                await _service.UpdateAsync(position);
                return RedirectToAction("Index");
            }
            return View(position);
        }

        [HttpGet]
        public async Task<IActionResult> Search(string searchTerm, string category)
        {
            var positions = await _service.GetAllAsync();

            if (!string.IsNullOrWhiteSpace(searchTerm))
            {
                positions = positions
                    .Where(position => position.JobTitle.ToLower().Contains(searchTerm.ToLower()))
                    .ToList();
            }

            if (!string.IsNullOrWhiteSpace(category) && category != "All")
            {
                positions = positions
                    .Where(position => position.Country.ToLower() == category.ToLower())
                    .ToList();
            }

            ViewData["Category"] = category ?? "All";

            return View("Index", positions);
        }
    }
}

TheScouts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Scouts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TheScouts.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <svg class="d-none">
        <symbol id="twitter" viewBox="0 0 16 16">
            <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
        </symbol>
        <symbol id="facebook" viewBox="0 0 16 16">
            <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
        </symbol>
    </svg>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom p-4">
            <div class="container-fluid d-flex justify-content-between">
                <div>
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">The Scouts</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse d-flex justify-content-center">
                    <ul class="navbar-nav" style="gap: 10px;">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Faq" asp-action="Index">FAQ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jobs" asp-action="Index">Jobs</a>
                        </li>
                        @if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Create">Contact</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Application" asp-action="Index">Applications</a>
                            </li>
                        }
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    @Html.ActionLink("Logout", "Logout", "Account", new { }, new { @class = "btn button-primary" })
                }
                else
                {
                    <div class="d-flex authentication-buttons">
                        @Html.ActionLink("Login", "Login", "Account", new { }, new { @class = "btn button-primary" })
                        @Html.ActionLink("Register", "Register", "Account", new { }, new { @class = "btn button-primary" })
                    </div>
                }
            </div>
        </nav>
    </header>
    <div class="container main">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="container">
        <div class="row border-top py-4 border-bottom d-flex justify-content-between align-items-center">
            <div class="col-6 col-md-2">
                <ul class="navbar-nav d-flex flex-row" style="gap: 70px;">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Faq" asp-action="Index">FAQ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Jobs" asp-action="Index">Jobs</a>
                    </li>
                    @if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Create">Contact</a>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Application" asp-action="Index">Applications</a>
                        </li>
                    }
                </ul>
            </div>
            <div class="col-md-5 offset-md-5">
                @using (Html.BeginForm("Create", "Newsletter", FormMethod.Post))
                {
                    <h5>Subscribe to our newsletter</h5>
                    <p>Stay career-ready with our monthly job updates.</p>
                    <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                        <label for="newsletterEmail" class="visually-hidden">Email address</label>
                        <input id="newsletterEmail" name="email" type="text" class="form-control" placeholder="Email address">
                        @Html.ValidationMessage("email", new { @class = "text-danger" })
                        <button class="btn btn-primary" type="submit" style="background-color: #212529; border-color: #212529; ">Subscribe</button>
                    </div>
                }
            </div>
        </div>
        <div class="d-flex flex-column flex-sm-row justify-content-between pt-4 pb-3">
            <p>&copy; 2024 The Scouts. All rights reserved.</p>
            <ul class="list-unstyled d-flex">
                <li class="ms-4"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter" /></svg></a></li>
                <li class="ms-4"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram" /></svg></a></li>
                <li class="ms-4"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook" /></svg></a></li>
            </ul>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="https://unpkg.com/autosize@4.0.2/dist/autosize.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TheScouts/Views/Shared/_SuccessMessage.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="display-6 mt-5">@ViewBag.SuccessMessage</h1>